CREATE TABLE ibge_foods2 (
                             id BIGSERIAL PRIMARY KEY,

                             Codigo INT,
                             descricacao_do_alimento VARCHAR(255),
                             Categoria VARCHAR(80),
                             Codigo_de_preparacao INT,
                             descricao_da_preparacao VARCHAR(255),

                             Energia_kcal VARCHAR(10),
                             Proteina_g VARCHAR(10),
                             Lipidios_totais_g VARCHAR(10),
                             Carboi_drato_g VARCHAR(10),
                             Fibra_alimentar_total_g VARCHAR(10),
                             Coles_terol_mg VARCHAR(10),
                             AG_Satura_dos_g VARCHAR(10),
                             AG_Mono_g VARCHAR(10),
                             AG_Poli_g VARCHAR(10),
                             AG_Lino_leico_g VARCHAR(10),
                             AG_Linole_nico_g VARCHAR(10),
                             AG_Trans_total_g VARCHAR(10),
                             Acucar_total_g VARCHAR(10),
                             Acucar_de_adicacao_g VARCHAR(10),
                             Calcio_mg VARCHAR(10),
                             Mag_nesio_mg VARCHAR(10),
                             Man_ganes_mg VARCHAR(10),
                             Fosforo_mg VARCHAR(10),
                             Ferro_mg VARCHAR(10),
                             Sodio_mg VARCHAR(10),
                             Sodio_de_adicao_mg VARCHAR(10),
                             Potas_sio_mg VARCHAR(10),
                             Co_bre_mg VARCHAR(10),
                             Zinco_mg VARCHAR(10),
                             Sele_nio_mcg VARCHAR(10),
                             Reti_nol_mcg VARCHAR(10),
                             Vitami_na_A_RAE_mcg VARCHAR(10),
                             Tiami_na_mg VARCHAR(10),
                             Ribofla_vina_mg VARCHAR(10),
                             Niaci_na_mg VARCHAR(10),
                             Niaci_na_NE_mg VARCHAR(10),
                             Pirido_xina_mg VARCHAR(10),
                             Coba_lami_na_mcg VARCHAR(10),
                             Folato_DFE_mcg VARCHAR(10),
                             Vitami_na_D_mcg VARCHAR(10),
                             Vitami_na_E_mg VARCHAR(10),
                             Vitami_na_C_mg VARCHAR(10),

                             slug VARCHAR(255),

                             created_at TIMESTAMP NULL DEFAULT NULL,
                             updated_at TIMESTAMP NULL DEFAULT NULL
);